"""Native-shell login completion: ``GET /auth/native-complete``.

The mobile shells drive browser-based logins through an OS auth surface
(Android Auth Tab / iOS ``ASWebAuthenticationSession``) whose cookie jar
is isolated from the shell's WebView. This endpoint is the completion
leg of that flow: the shell opens it in the auth surface, whatever
authentication fronts the server runs in a real browser context, and
once the request finally arrives here authenticated, the server hands a
credential back to the app through a fixed custom-scheme redirect that
closes the auth surface.

The credential depends on the active auth mode:

- **header mode** (e.g. Databricks Apps, where a front-door proxy
  authenticates every request): relays the proxy-forwarded per-user
  access token (``X-Forwarded-Access-Token`` by convention) so the app
  can authenticate to the same front door natively.
- **oidc / accounts mode**: mints a session JWT — the same shape the
  session-cookie validator accepts — so the app can install it as the
  WebView session cookie.

The redirect target is a fixed constant (never caller-supplied), so
this endpoint cannot be aimed at an attacker-chosen URI. The ``state``
value is an opaque nonce generated by the app; the app drops any
callback whose state does not match its one in-flight login.
"""

from __future__ import annotations

import logging
import os
import re
from urllib.parse import quote, urlencode

from fastapi import APIRouter, Request
from starlette.responses import JSONResponse, RedirectResponse, Response

from omnigent.server.auth import UnifiedAuthProvider

_logger = logging.getLogger(__name__)

# Fixed completion target. The scheme/host pair is registered by the
# mobile shells; deliberately NOT caller-configurable per request so the
# endpoint can never be used to relay a credential to a foreign URI.
_CALLBACK_URI = "omnigent://auth-callback"

# Proxy-forwarded per-user access token read in header mode. Databricks
# Apps convention; other front doors can point the server at their
# equivalent header.
_FORWARDED_TOKEN_HEADER_ENV = "OMNIGENT_FORWARDED_TOKEN_HEADER"
_DEFAULT_FORWARDED_TOKEN_HEADER = "X-Forwarded-Access-Token"

# The app's nonce: URL-safe base64 alphabet, bounded. Anything else is
# rejected outright rather than echoed into the redirect.
_STATE_RE = re.compile(r"^[A-Za-z0-9_-]{8,128}$")

# Session-JWT lifetime when no cookie config supplies one (defensive —
# both cookie modes always carry ``session_ttl_hours``).
_FALLBACK_TTL_SECONDS = 8 * 3600


def resolve_forwarded_token_header() -> str:
    """Resolve the header carrying the proxy-forwarded user token.

    :returns: ``OMNIGENT_FORWARDED_TOKEN_HEADER`` when set and non-blank,
        else ``X-Forwarded-Access-Token``.
    """
    raw = os.environ.get(_FORWARDED_TOKEN_HEADER_ENV)
    if raw and raw.strip():
        return raw.strip()
    return _DEFAULT_FORWARDED_TOKEN_HEADER


def create_native_auth_router(auth_provider: UnifiedAuthProvider) -> APIRouter:
    """Create the router serving ``/native-complete`` (mounted at ``/auth``).

    Mounted for every :class:`UnifiedAuthProvider` mode — unlike the
    login routers, which are per-mode — because header mode has no other
    ``/auth`` surface yet is exactly the mode that needs this endpoint.

    :param auth_provider: The active provider; supplies identity
        extraction and (in cookie modes) session-JWT minting.
    :returns: A FastAPI router with the single completion route.
    """
    router = APIRouter()
    forwarded_token_header = resolve_forwarded_token_header()

    def _redirect_to_app(params: dict[str, str]) -> Response:
        response = RedirectResponse(
            url=f"{_CALLBACK_URI}?{urlencode(params)}",
            status_code=302,
        )
        # The Location carries a credential — keep it out of every cache.
        response.headers["Cache-Control"] = "no-store"
        return response

    @router.get("/native-complete")
    async def native_complete(request: Request) -> Response:
        """Complete a native-shell login with a custom-scheme redirect.

        :param request: Carries ``state`` (the app's nonce) and, once
            authenticated, whatever identity the active mode uses.
        :returns: 302 to the app's fixed callback URI with the
            credential (or ``error=no_token`` when header mode has no
            forwarded token); 302 to the login page when a cookie-mode
            request is unauthenticated; 400 on a malformed state; 401
            when header mode sees no identity.
        """
        state = request.query_params.get("state") or ""
        if not _STATE_RE.fullmatch(state):
            return JSONResponse(
                status_code=400,
                content={"error": "Missing or malformed state parameter"},
            )

        user_id = auth_provider.get_user_id(request)
        if user_id is None:
            login_url = auth_provider.login_url
            if login_url:
                # Cookie modes own their login UX — bounce through it and
                # return here once the session cookie exists.
                return_to = quote(f"/auth/native-complete?state={state}", safe="")
                return RedirectResponse(
                    url=f"{login_url}?return_to={return_to}",
                    status_code=302,
                )
            # Header mode: an unauthenticated request means the fronting
            # proxy let it through without identity — nothing to relay.
            return JSONResponse(status_code=401, content={"error": "not authenticated"})

        if auth_provider._source == "header":
            token = (request.headers.get(forwarded_token_header) or "").strip()
            if not token:
                # Authenticated identity but no per-user token to relay
                # (proxy not configured to forward one). Tell the app so
                # it can fall back instead of waiting.
                _logger.info(
                    "native-complete: no %s to relay for %s",
                    forwarded_token_header,
                    user_id,
                )
                return _redirect_to_app({"state": state, "error": "no_token"})
            return _redirect_to_app(
                {"state": state, "token_type": "bearer", "token": token}
            )

        cookie_config = (
            auth_provider._oidc_config
            if auth_provider._source == "oidc"
            else auth_provider._accounts_config
        )
        ttl_seconds = (
            cookie_config.session_ttl_hours * 3600
            if cookie_config is not None
            else _FALLBACK_TTL_SECONDS
        )
        token = auth_provider.mint_runner_token(user_id, ttl_seconds)
        if not token:
            # Reserved identity or missing cookie config — nothing safe to
            # hand out.
            return _redirect_to_app({"state": state, "error": "no_token"})
        return _redirect_to_app({"state": state, "token_type": "session", "token": token})

    return router
